from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required as smr
from kanisa.views.sermons import (SermonIndexView,
                                  SermonSeriesDetailView,
                                  SermonSeriesCreateView,
                                  SermonSeriesUpdateView,
                                  SermonSeriesCompleteView,
                                  SermonCreateView,
                                  SermonUpdateView,
                                  SermonSpeakerIndexView,
                                  SermonSpeakerCreateView,
                                  SermonSpeakerUpdateView)

urlpatterns = patterns('',
                       url(r'^$',
                           smr(SermonIndexView.as_view()),
                           {},
                           'kanisa_manage_sermons'),
                       url(r'^series/(?P<pk>\d+)$$',
                           smr(SermonSeriesDetailView.as_view()),
                           {},
                           'kanisa_manage_sermons_series_detail'),
                       url(r'^series/create/$',
                           smr(SermonSeriesCreateView.as_view()),
                           {},
                           'kanisa_manage_sermons_series_create'),
                       url(r'^series/edit/(?P<pk>\d+)$',
                           smr(SermonSeriesUpdateView.as_view()),
                           {},
                           'kanisa_manage_sermons_series_update'),
                       url(r'^complete/(?P<sermon_id>\d+)$',
                           smr(SermonSeriesCompleteView.as_view()),
                           {},
                           'kanisa_manage_sermons_series_complete'),
                       url(r'^sermon/create/$',
                           smr(SermonCreateView.as_view()),
                           {},
                           'kanisa_manage_sermons_individual_create'),
                       url(r'^sermon/edit/(?P<pk>\d+)$',
                           smr(SermonUpdateView.as_view()),
                           {},
                           'kanisa_manage_sermons_individual_update'),
                       url(r'^speaker/$',
                           smr(SermonSpeakerIndexView.as_view()),
                           {},
                           'kanisa_manage_sermons_speaker'),
                       url(r'^speaker/create/$',
                           smr(SermonSpeakerCreateView.as_view()),
                           {},
                           'kanisa_manage_sermons_speaker_create'),
                       url(r'^speaker/edit/(?P<pk>\d+)$',
                           smr(SermonSpeakerUpdateView.as_view()),
                           {},
                           'kanisa_manage_sermons_speaker_update'),
                       )
