from django.conf.urls import patterns, url
from kanisa.views.banners import (BannerCreateView,
                                  BannerUpdateView,
                                  InactiveBannerManagementView,
                                  BannerManagementView,
                                  RetireBannerView)

urlpatterns = patterns('',
                       url(r'^$',
                           BannerManagementView.as_view(),
                           {},
                           'kanisa_manage_banners'),
                       url(r'^inactive/$',
                           InactiveBannerManagementView.as_view(),
                           {},
                           'kanisa_manage_banners_inactive'),
                       url(r'^create/$',
                           BannerCreateView.as_view(),
                           {},
                           'kanisa_manage_banners_create'),
                       url(r'^edit/(?P<pk>\d+)$',
                           BannerUpdateView.as_view(),
                           {},
                           'kanisa_manage_banners_update'),
                       url(r'^retire/(?P<banner_id>\d+)$',
                           RetireBannerView.as_view(),
                           {},
                           'kanisa_manage_banners_retire'),
                       )
