from django.conf.urls import patterns, url
from kanisa.views.navigation import (NavigationElementIndexView,
                                     NavigationElementCreateView,
                                     NavigationElementUpdateView,
                                     NavigationElementMoveDownView,
                                     NavigationElementMoveUpView)


urlpatterns = patterns('',
                       url(r'^$',
                           NavigationElementIndexView.as_view(),
                           {},
                           'kanisa_manage_navigation'),
                       url(r'^create/$',
                           NavigationElementCreateView.as_view(),
                           {},
                           'kanisa_manage_navigation_create'),
                       url(r'^edit/(?P<pk>\d+)$',
                           NavigationElementUpdateView.as_view(),
                           {},
                           'kanisa_manage_navigation_update'),
                       url(r'^down/(?P<pk>\d+)$',
                           NavigationElementMoveDownView.as_view(),
                           {},
                           'kanisa_manage_navigation_move_down'),
                       url(r'^up/(?P<pk>\d+)$',
                           NavigationElementMoveUpView.as_view(),
                           {},
                           'kanisa_manage_navigation_move_up'),
                       )
