from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^permissions/$',
                           'kanisa.views.xhr.assign_permission',
                           {},
                           'kanisa_manage_xhr_assign_permission'),
                       url(r'^pages/create/$',
                           'kanisa.views.xhr.create_page',
                           {},
                           'kanisa_manage_xhr_create_page'),
                       url(r'^pages/list/$',
                           'kanisa.views.xhr.list_pages',
                           {},
                           'kanisa_manage_xhr_list_pages'),
                       url(r'^sermons/markcomplete/$',
                           'kanisa.views.xhr.mark_sermon_series_complete',
                           {},
                           'kanisa_manage_xhr_sermon_series_complete'),
                       url(r'^diary/schedule/update/$',
                           'kanisa.views.xhr.schedule_regular_event',
                           {},
                           'kanisa_manage_xhr_diary_schedule_regular'),
                       url(r'^diary/schedule/fetch/(?P<date>\d+)/$',
                           'kanisa.views.xhr.get_events',
                           {},
                           'kanisa_manage_xhr_diary_get_schedule'),
                       )
