# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 20:45
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kanisa', '0003_django_110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularevent',
            name='pattern',
            field=recurrence.fields.RecurrenceField(blank=True, verbose_name=b'Timetable'),
        ),
    ]
