# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanisa', '0004_regularevent_make_pattern_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularevent',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='contact',
        ),
        migrations.DeleteModel(
            name='EventContact',
        ),
    ]
